Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,7 +22,7 @@ env:
     -nomake examples -nomake tests -nomake benchmarks -nomake manual-tests -nomake minimal-static-tests -no-feature-gssapi -no-feature-accessibility
     -no-feature-sql -no-feature-graphicsframecapture -DFEATURE_no_direct_extern_access=ON -unity-build
   EXTRA_FLAGS: -no-feature-qml-network -no-feature-qml-ssl -no-feature-quickcontrols2-fusion
-  QT_BASE_CHERRY_PICK: 712956 524178 644402 680266 754065 753848 752561 754129 754130 751156 751157 754389 758382 758221 737729 756473 757958 758243 758244 757959 758793 #757976
+  QT_BASE_CHERRY_PICK: 712956 524178 644402 680266 754065 753848 752561 754129 754130 751156 751157 754389 758382 758221 737729 756473 757958 758243 758244 757959 758793 757976
   QT_DECLARATIVE_CHERRY_PICK: 622692 695153 727806 743838 754298 754121 754107 753876 757036
     
 on:
@@ -104,7 +104,7 @@ jobs:
               [ "$status" = "MERGED" ] && echo "Change $change is already merged" || echo "Change $change status: $status"
               [ -z "$commit" ] && { echo "::error::Change $change not found in $repo"; exit 1; }
               git fetch https://codereview.qt-project.org/qt/$repo "$commit" || exit 1
-              git cherry-pick --no-commit FETCH_HEAD || { echo "::error::Cherry-pick failed for $change"; git cherry-pick --abort; exit 1; }
+              git cherry-pick -Xtheirs --no-commit FETCH_HEAD || { echo "::error::Cherry-pick failed for $change"; git cherry-pick --abort; exit 1; }
             done
           }
           [ -n "${QT_BASE_CHERRY_PICK}" ] && apply_changes qtbase ${QT_BASE_CHERRY_PICK}
@@ -206,7 +206,7 @@ jobs:
               [ "$status" = "MERGED" ] && echo "Change $change is already merged" || echo "Change $change status: $status"
               [ -z "$commit" ] && { echo "::error::Change $change not found in $repo"; exit 1; }
               git fetch https://codereview.qt-project.org/qt/$repo "$commit" || exit 1
-              git cherry-pick --no-commit FETCH_HEAD || { echo "::error::Cherry-pick failed for $change"; git cherry-pick --abort; exit 1; }
+              git cherry-pick -Xtheirs --no-commit FETCH_HEAD || { echo "::error::Cherry-pick failed for $change"; git cherry-pick --abort; exit 1; }
             done
           }
           [ -n "${QT_BASE_CHERRY_PICK}" ] && apply_changes qtbase ${QT_BASE_CHERRY_PICK}
@@ -335,7 +335,7 @@ jobs:
               [ "$status" = "MERGED" ] && echo "Change $change is already merged" || echo "Change $change status: $status"
               [ -z "$commit" ] && { echo "::error::Change $change not found in $repo"; exit 1; }
               git fetch https://codereview.qt-project.org/qt/$repo "$commit" || exit 1
-              git cherry-pick --no-commit FETCH_HEAD || { echo "::error::Cherry-pick failed for $change"; git cherry-pick --abort; exit 1; }
+              git cherry-pick -Xtheirs --no-commit FETCH_HEAD || { echo "::error::Cherry-pick failed for $change"; git cherry-pick --abort; exit 1; }
             done
           }
           [ -n "${QT_BASE_CHERRY_PICK}" ] && apply_changes qtbase ${QT_BASE_CHERRY_PICK}
@@ -415,7 +415,7 @@ jobs:
               [ "$status" = "MERGED" ] && echo "Change $change is already merged" || echo "Change $change status: $status"
               [ -z "$commit" ] && { echo "::error::Change $change not found in $repo"; exit 1; }
               git fetch https://codereview.qt-project.org/qt/$repo "$commit" || exit 1
-              git cherry-pick --no-commit FETCH_HEAD || { echo "::error::Cherry-pick failed for $change"; git cherry-pick --abort; exit 1; }
+              git cherry-pick -Xtheirs --no-commit FETCH_HEAD || { echo "::error::Cherry-pick failed for $change"; git cherry-pick --abort; exit 1; }
             done
           }
           [ -n "${QT_BASE_CHERRY_PICK}" ] && apply_changes qtbase ${QT_BASE_CHERRY_PICK}
